# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 031bcaa25022256002e6ffecdd7bdc4ed4f18790a54ed5f1365d1bc66ad63b8329e247fe085da42876e97ddd3f8025dcadaebf60dd50e7f49fb199f5b5a1784d

test:
  secret_key_base: 7dba52e461dfb04ad0e9ee231db991f4fe99946cdaf8364831443eff2b572e087f72607831a657fb7aca06e2c6b23dc711c6cf571f1c863530b9816d94c3d825

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
